Update git submodules
* Update skins/Vector from branch 'wmf/1.38.0-wmf.16'
  to 79b33f27150544839c5b426157d690ab99894473
  - Fix TypeError: document.querySelectorAll(...).forEach is not a function
    
    Bug: T298910
    Change-Id: Iaa67f36278af7805c5d915737d6b30e98b3f8484
    (cherry picked from commit d9ef1ad66d9e3a8e7a7387e050e322bdde018ced)