Update git submodules
* Update extensions/FlaggedRevs from branch 'wmf/1.38.0-wmf.23'
  to 616f4c0d06f0afaf65c2b24cda03d879e01aa572
  - ext.flaggedRevs.review: Restore tolerance when setting "disabled" prop
    
    Follows-up 74726ea8, which removed needless use of jQuery. One of the
    things that this was doing is silently tolerate when selector yielded
    an empty collection and no-op operations like `prop()`.
    
    The comment hinted at its optional nature already, which I failed
    to notice/realize.
    
    Fixes:
    > TypeError: Cannot set properties of null (setting 'disabled')
    
    Change-Id: I1dcc8316c691e96ce1acee5b4b57dadb2ecf60d6
    (cherry picked from commit 3f9e352ca2eb843ece600ebfa0072b3cf86e7066)